import React from "react";
import {
  Accordion,
  AccordionItem,
  AccordionItemHeading,
  AccordionItemButton,
  AccordionItemPanel,
} from "react-accessible-accordion";
import "react-accessible-accordion/dist/fancy-example.css";
import "../styles.scss";
import useLeftToRightSwipe from "../animation/useLeftToRightSwipe";
import Footer from "./Footer";
const FAQs = () => {
  useLeftToRightSwipe(".accord-ani");
  return (
    <>
      <div className="faq-container">
        <h2>Frequently Asked Questions (FAQs)</h2>
        <p>
          Here are some common questions and answers about our freelancer
          calculator and logo design services.
        </p>
        <div className="faq-accord">
          <Accordion>
            <AccordionItem className="accord-ani">
              <AccordionItemHeading>
                <AccordionItemButton>
                  Can I request a custom logo design?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                Yes, our services include custom logo design tailored to your
                specific needs.
              </AccordionItemPanel>
            </AccordionItem>
            <AccordionItem>
              <AccordionItemHeading>
                <AccordionItemButton>
                  How much does your logo design service cost?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                The cost of our logo design service depends on various factors
                such as the complexity of the design and the selected package.
                Please refer to our pricing section for detailed information.
              </AccordionItemPanel>
            </AccordionItem>
            <AccordionItem className="accord-ani">
              <AccordionItemHeading>
                <AccordionItemButton>
                  Are the prices generated by your freelancer calculator fixed?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                The prices generated by our freelancer calculator provide
                estimates based on the information provided. Final prices may
                vary based on specific project requirements.
              </AccordionItemPanel>
            </AccordionItem>
            <AccordionItem>
              <AccordionItemHeading>
                <AccordionItemButton>
                  Do you offer any discount offers?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                Yes, we occasionally offer discount promotions. Keep an eye on
                our website or subscribe to our newsletter to stay updated on
                any ongoing offers.
              </AccordionItemPanel>
            </AccordionItem>

            <AccordionItem className="accord-ani">
              <AccordionItemHeading>
                <AccordionItemButton>
                  What file formats do you provide for the logo designs?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                We provide logo designs in various formats, including PNG, JPEG,
                and PDF. These formats are suitable for different use cases such
                as printing, web, and transparent backgrounds.
              </AccordionItemPanel>
            </AccordionItem>
            <AccordionItem>
              <AccordionItemHeading>
                <AccordionItemButton>
                  How many revisions are included in the logo design packages?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                The number of revisions included in each logo design package
                varies. Please check the details of your selected package for
                information on the revision limits.
              </AccordionItemPanel>
            </AccordionItem>
            <AccordionItem className="accord-ani">
              <AccordionItemHeading>
                <AccordionItemButton>
                  Can I use the logo for commercial purposes?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                Yes, once the logo design is finalized and delivered, you have
                full rights to use it for commercial purposes. We provide you
                with the necessary files and permissions to use the logo as you
                see fit.
              </AccordionItemPanel>
            </AccordionItem>
            <AccordionItem>
              <AccordionItemHeading>
                <AccordionItemButton>
                  What services do you offer for website design?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                We offer a range of website design services, including but not
                limited to responsive design, e-commerce integration, content
                management systems (CMS), and custom development. Contact us for
                more details about your specific website design needs.
              </AccordionItemPanel>
            </AccordionItem>

            <AccordionItem className="accord-ani">
              <AccordionItemHeading>
                <AccordionItemButton>
                  Can I provide my own content for the website?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                Yes, you can provide your own content for the website. We
                welcome your input and will work closely with you to ensure the
                website reflects your brand and messaging.
              </AccordionItemPanel>
            </AccordionItem>

            <AccordionItem>
              <AccordionItemHeading>
                <AccordionItemButton>
                  What file formats are available for flyer designs?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                We provide flyer designs in high-resolution formats such as PDF,
                JPEG, and PNG. These formats are suitable for both online and
                print use.
              </AccordionItemPanel>
            </AccordionItem>

            <AccordionItem className="accord-ani">
              <AccordionItemHeading>
                <AccordionItemButton>
                  Do you offer printing services for business cards?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                Currently, we focus on providing design services, and we
                recommend reputable printing services for your business cards.
                We can guide you on the best practices for printing and refer
                you to trusted printing partners.
              </AccordionItemPanel>
            </AccordionItem>

            <AccordionItem>
              <AccordionItemHeading>
                <AccordionItemButton>
                  How long does it take to complete a business card design?
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                The turnaround time for business card design depends on the
                complexity of the project and the number of revisions. We strive
                to provide timely and efficient design services to meet your
                business needs.
              </AccordionItemPanel>
            </AccordionItem>
          </Accordion>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default FAQs;
