import React, { useState, useEffect } from "react";
import "../styles.scss";
import { FaAngleUp, FaAngleDown } from "react-icons/fa";
import useZoomInAnimation from "../animation/useZoomInAnimation";
import Footer from "./Footer";
const FAQs = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  });
  useZoomInAnimation(".faq-container");
  const Faqs = [
    {
      id: 1,
      question: "   How much does your logo design service cost?",
      answer:
        " The cost of our logo design service depends on various factors such as the complexity of the design and the selected package.Please refer to our pricing section for detailed information.",
    },
    {
      id: 2,
      question: "    Can I request a custom logo design?",
      answer:
        "    Yes, our services include custom logo design tailored to your specific needs.",
    },
    {
      id: 3,
      question:
        "   Are the prices generated by your freelancer calculator fixed?",
      answer:
        "The prices generated by our freelancer calculator provide estimates based on the information provided. Final prices may vary based on specific project requirements.",
    },
    {
      id: 4,
      question: "  What services do you offer for website design?",
      answer:
        "We offer a range of website design services, including but not limited to responsive design, e-commerce integration, content management systems (CMS), and custom development. Contact us for more details about your specific website design needs.",
    },
    {
      id: 5,
      question: "What file formats do you provide for the logo designs?",
      answer:
        "We provide logo designs in various formats, including PNG, JPEG, and PDF. These formats are suitable for different use cases such as printing, web, and transparent backgrounds.",
    },
    {
      id: 6,
      question: "    Can I provide my own content for the website?",
      answer:
        "Yes, you can provide your own content for the website. We welcome your input and will work closely with you to ensure the website reflects your brand and messaging.",
    },
    {
      id: 7,
      question: " How long does it take to complete a business card design?",
      answer:
        "The turnaround time for business card design depends on the complexity of the project and the number of revisions. We strive to provide timely and efficient design services to meet your business needs.",
    },
  ];

  const [openFaqs, setOpenFaqs] = useState(null);

  const handleFaqsClick = (FaqsId) => {
    setOpenFaqs((prevOpenFaqs) => (prevOpenFaqs === FaqsId ? null : FaqsId));
  };
  return (
    <>
      <div className="faq-container">
        <h2>Frequently Asked Questions (FAQs)</h2>
        <p>
          Here are some common questions and answers about our freelancer
          calculator and logo design services.
        </p>
        <div className="faq-accord ">
          {Faqs.map((Faqs) => (
            <div key={Faqs.id} className="Faqs-item">
              <div
                className={`Faqs-header ${openFaqs === Faqs.id ? "open" : ""}`}
                onClick={() => handleFaqsClick(Faqs.id)}
              >
                <h4>
                  {Faqs.question}{" "}
                  {openFaqs === Faqs.id ? <FaAngleUp /> : <FaAngleDown />}
                </h4>
              </div>
              <div
                className={`Faqs-content ${openFaqs === Faqs.id ? "open" : ""}`}
              >
                <article>{Faqs.answer}</article>
              </div>
            </div>
          ))}
        </div>
      </div>
      <Footer />
    </>
  );
};

export default FAQs;
